[platformio]
default_envs = nucleo_h753zi, esp32s3
src_dir = .

[env]
build_flags =
    -DDEBUG=1

[env:nucleo_h753zi]
platform         = ststm32
board            = nucleo_h753zi
framework        = arduino
monitor_speed    = 115200
build_src_filter = -<*> +<NUCLEO/src/>
lib_deps         = nrf24/RF24

[env:esp32s3]
platform         = espressif32
board            = esp32-s3-devkitc-1
framework        = arduino
monitor_speed    = 115200
monitor_rts      = 0
monitor_dtr      = 0
build_flags      =
    ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<ESP/src/>

[env:esp32s3_cal]
platform         = espressif32
board            = esp32-s3-devkitc-1
framework        = arduino
monitor_speed    = 115200
monitor_rts      = 0
monitor_dtr      = 0
build_flags      =
    ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = -<*> +<ESP/tx/>